### ISSUE TITLE
碰撞箱会添加吗

### ISSUE THREAD

**Issue by joe-vettek** [Snownee/Kaleido#1]
虽然成功的放出了方块，不过可惜的是没有碰撞箱，让人有点遗憾。

**Comment by Snownee** [comment]
https://github.com/KaleidoMC/Kaleido/wiki/Customizing-Blocks#shape

你可以参考这一部分添加

**Comment by joe-vettek** [comment]
感谢，我是从discord来的，没注意wiki有好几页，不过感觉需要一段代码来完成这个工作，6000个太多了，虽然coc处理方式就是当作一个block。

**Comment by Snownee** [comment]
你是指cocricot没有碰撞啊。以后会支持的。

**Comment by joe-vettek** [comment]
好的，非常期待。我朋友对12..2恋恋不舍就是因为coc了，但我觉得高版本有更多新的有趣内容。
顺便叨扰一下，料理工艺会升级到1.16.5吗？还是就只会留存果树这个模组。

**Comment by Snownee** [comment]
暂时不会
